import Link from "next/link";
import "./globals.css";

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { MotionPathPlugin } from "gsap/MotionPathPlugin";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

gsap.registerPlugin(useGSAP);
gsap.registerPlugin(MotionPathPlugin);

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="tc-new-price">
      <body className={`antialiased`}>
        <main className="h-screen flex justify-center items-center">
          <Link href="/" className="fixed top-5 left-5 text-green-500 z-50">
            Return Home
          </Link>
          {children}
        </main>
      </body>
    </html>
  );
}
